#!/bin/bash

#20200803 KM4ACK

WHO=$(whoami)

#stop any running services
sudo /usr/bin/pkill kissattach
sudo /usr/bin/rfcomm release /dev/rfcomm0
sudo /usr/bin/pkill aprx

#search for TNC
echo "scanning for TNC"
MAC=$(hcitool scan | grep Mobilinkd | awk '{print $1}')
TNC=$(hcitool scan | grep TNC2)
if [ -z "$TNC" ]; then
CONNECT="$MAC 6"
else
CONNECT="$MAC"
fi

if [ -z "$MAC" ]; then
echo "TNC Not Found"
exit 1
else
echo "Connecting"
sudo rfcomm bind /dev/rfcomm0 $CONNECT
sleep 2
sudo /sbin/aprx
fi

