#!/bin/bash

#20200803 KM4ACK

WHO=$(whoami)

#stop any running services
sudo /usr/bin/pkill kissattach
sudo /usr/bin/rfcomm release /dev/rfcomm0

#search for TNC
echo "scanning for TNC"
MAC=$(hcitool scan | grep Mobilinkd | awk '{print $1}')
if [ -z "$MAC" ]; then
echo "TNC Not Found"
exit 1
else
echo "Connecting"
sudo rfcomm bind /dev/rfcomm0 $MAC
sleep 1
sudo kissattach /dev/rfcomm0 wl2k
RF=$(ls /dev | grep rfcomm)
KA=$(pidof kissattach)
	if [ -z "$RF" ] || [ -z "$KA" ]; then
	echo "Not Connected"
	else
	echo "Connected"
	fi
fi

#restart pat server
sudo systemctl restart pat@pi
